{% set name = "frozenlist" %}
{% set version = "1.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: effc641518696471cf4962e8e32050133bc1f7b2851ae8fd0cb8797dd70dc202

build:
  number: 0
  noarch: python             # [use_noarch]
  track_features:            # [use_noarch]
    - frozenlist_no_compile  # [use_noarch]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv                                      # [not use_noarch]
    - {{ PYTHON }} -m pip install . --no-deps -vv  --config-settings=pure-python=true  # [use_noarch]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python {{ python_min }}     # [use_noarch]
    - python                      # [not use_noarch]
  host:
    - python {{ python_min }}     # [use_noarch]
    - python                      # [not use_noarch]
    - pip
    - cython
    - expandvars
    - setuptools >=47
  run:
    - python >={{ python_min }}   # [use_noarch]
    - python                      # [not use_noarch]

test:
  imports:
    - frozenlist
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}     # [use_noarch]

about:
  home: https://github.com/aio-libs/frozenlist
  summary: A list-like structure which implements collections.abc.MutableSequence
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
